
interface _GlobalComponents {
      'AgentInvoiceDetails': typeof import("../components/agent/Invoice/details.vue")['default']
    'AgentInvoice': typeof import("../components/agent/Invoice/index.vue")['default']
    'AgentAddagent': typeof import("../components/agent/addagent.vue")['default']
    'AgentAgentwizard': typeof import("../components/agent/agentwizard.vue")['default']
    'AgentAllagent': typeof import("../components/agent/allagent.vue")['default']
    'AgentEditagent': typeof import("../components/agent/editagent.vue")['default']
    'AgentProfiledataAbout': typeof import("../components/agent/profiledata/about.vue")['default']
    'AgentProfiledata': typeof import("../components/agent/profiledata/index.vue")['default']
    'AgentProfiledataPropertyandearning': typeof import("../components/agent/profiledata/propertyandearning.vue")['default']
    'CommonBreadcrumb': typeof import("../components/common/breadcrumb/index.vue")['default']
    'CommonChartBarchart': typeof import("../components/common/chart/barchart.vue")['default']
    'CommonChartEarning': typeof import("../components/common/chart/earning.vue")['default']
    'CommonChartIncomechart': typeof import("../components/common/chart/incomechart.vue")['default']
    'CommonChartRevenue': typeof import("../components/common/chart/revenue.vue")['default']
    'CommonChartUsers': typeof import("../components/common/chart/users.vue")['default']
    'CommonInputfieldsNumberfield': typeof import("../components/common/inputfields/numberfield.vue")['default']
    'CommonInputfieldsStatusfield': typeof import("../components/common/inputfields/statusfield.vue")['default']
    'CommonInputfieldsTextarea': typeof import("../components/common/inputfields/textarea.vue")['default']
    'CommonInputfieldsTextfield': typeof import("../components/common/inputfields/textfield.vue")['default']
    'CommonListdata': typeof import("../components/common/listdata.vue")['default']
    'CommonMapsWorldmap': typeof import("../components/common/maps/worldmap.vue")['default']
    'CommonSocialicon': typeof import("../components/common/socialicon.vue")['default']
    'Customizer': typeof import("../components/customizer.vue")['default']
    'DashboardAssignees': typeof import("../components/dashboard/assignees.vue")['default']
    'DashboardChart': typeof import("../components/dashboard/chart.vue")['default']
    'Dashboard': typeof import("../components/dashboard/index.vue")['default']
    'DashboardMyproperties': typeof import("../components/dashboard/myproperties.vue")['default']
    'DashboardReport': typeof import("../components/dashboard/report.vue")['default']
    'DashboardSalesdetails': typeof import("../components/dashboard/salesdetails.vue")['default']
    'DashboardSoldout': typeof import("../components/dashboard/soldout.vue")['default']
    'DashboardTimeline': typeof import("../components/dashboard/timeline.vue")['default']
    'LayoutCustomizer': typeof import("../components/layout/customizer.vue")['default']
    'LayoutFooter': typeof import("../components/layout/footer/index.vue")['default']
    'LayoutHeaderAttachment': typeof import("../components/layout/header/attachment.vue")['default']
    'LayoutHeader': typeof import("../components/layout/header/index.vue")['default']
    'LayoutHeaderMessage': typeof import("../components/layout/header/message.vue")['default']
    'LayoutHeaderNotification': typeof import("../components/layout/header/notification.vue")['default']
    'LayoutSidebar': typeof import("../components/layout/sidebar/index.vue")['default']
    'Loader': typeof import("../components/loader.vue")['default']
    'Login': typeof import("../components/login/index.vue")['default']
    'MapWorldmap': typeof import("../components/map/worldmap.vue")['default']
    'MypropertiesAddproperty': typeof import("../components/myproperties/addproperty.vue")['default']
    'MypropertiesEditproperty': typeof import("../components/myproperties/editproperty.vue")['default']
    'MypropertiesFavourites': typeof import("../components/myproperties/favourites.vue")['default']
    'MypropertiesListing': typeof import("../components/myproperties/listing.vue")['default']
    'MypropertiesPropertyDetails': typeof import("../components/myproperties/property-details.vue")['default']
    'Page404': typeof import("../components/page404.vue")['default']
    'Payment': typeof import("../components/payment/index.vue")['default']
    'Report': typeof import("../components/report/index.vue")['default']
    'ReportRevenue': typeof import("../components/report/revenue.vue")['default']
    'ReportSales': typeof import("../components/report/sales.vue")['default']
    'ReportTranaction': typeof import("../components/report/tranaction.vue")['default']
    'Signup': typeof import("../components/signup/index.vue")['default']
    'TypeAppartment': typeof import("../components/type/appartment.vue")['default']
    'TypeCondominium': typeof import("../components/type/condominium.vue")['default']
    'TypeCottage': typeof import("../components/type/cottage.vue")['default']
    'TypeFamily': typeof import("../components/type/family.vue")['default']
    'UserAdduser': typeof import("../components/user/adduser.vue")['default']
    'UserAllusers': typeof import("../components/user/allusers.vue")['default']
    'UserEdituser': typeof import("../components/user/edituser.vue")['default']
    'UserFormwizardFirsttab': typeof import("../components/user/formwizard/firsttab.vue")['default']
    'UserFormwizard': typeof import("../components/user/formwizard/index.vue")['default']
    'UserFormwizardSecondtab': typeof import("../components/user/formwizard/secondtab.vue")['default']
    'UserFormwizardThirdtab': typeof import("../components/user/formwizard/thirdtab.vue")['default']
    'UserProfileFriends': typeof import("../components/user/profile/friends.vue")['default']
    'UserProfile': typeof import("../components/user/profile/index.vue")['default']
    'UserProfileInstallment': typeof import("../components/user/profile/installment.vue")['default']
    'UserProfilePropertyandlearning': typeof import("../components/user/profile/propertyandlearning.vue")['default']
    'UserProfileUserfollowing': typeof import("../components/user/profile/userfollowing.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAgentInvoiceDetails': typeof import("../components/agent/Invoice/details.vue")['default']
    'LazyAgentInvoice': typeof import("../components/agent/Invoice/index.vue")['default']
    'LazyAgentAddagent': typeof import("../components/agent/addagent.vue")['default']
    'LazyAgentAgentwizard': typeof import("../components/agent/agentwizard.vue")['default']
    'LazyAgentAllagent': typeof import("../components/agent/allagent.vue")['default']
    'LazyAgentEditagent': typeof import("../components/agent/editagent.vue")['default']
    'LazyAgentProfiledataAbout': typeof import("../components/agent/profiledata/about.vue")['default']
    'LazyAgentProfiledata': typeof import("../components/agent/profiledata/index.vue")['default']
    'LazyAgentProfiledataPropertyandearning': typeof import("../components/agent/profiledata/propertyandearning.vue")['default']
    'LazyCommonBreadcrumb': typeof import("../components/common/breadcrumb/index.vue")['default']
    'LazyCommonChartBarchart': typeof import("../components/common/chart/barchart.vue")['default']
    'LazyCommonChartEarning': typeof import("../components/common/chart/earning.vue")['default']
    'LazyCommonChartIncomechart': typeof import("../components/common/chart/incomechart.vue")['default']
    'LazyCommonChartRevenue': typeof import("../components/common/chart/revenue.vue")['default']
    'LazyCommonChartUsers': typeof import("../components/common/chart/users.vue")['default']
    'LazyCommonInputfieldsNumberfield': typeof import("../components/common/inputfields/numberfield.vue")['default']
    'LazyCommonInputfieldsStatusfield': typeof import("../components/common/inputfields/statusfield.vue")['default']
    'LazyCommonInputfieldsTextarea': typeof import("../components/common/inputfields/textarea.vue")['default']
    'LazyCommonInputfieldsTextfield': typeof import("../components/common/inputfields/textfield.vue")['default']
    'LazyCommonListdata': typeof import("../components/common/listdata.vue")['default']
    'LazyCommonMapsWorldmap': typeof import("../components/common/maps/worldmap.vue")['default']
    'LazyCommonSocialicon': typeof import("../components/common/socialicon.vue")['default']
    'LazyCustomizer': typeof import("../components/customizer.vue")['default']
    'LazyDashboardAssignees': typeof import("../components/dashboard/assignees.vue")['default']
    'LazyDashboardChart': typeof import("../components/dashboard/chart.vue")['default']
    'LazyDashboard': typeof import("../components/dashboard/index.vue")['default']
    'LazyDashboardMyproperties': typeof import("../components/dashboard/myproperties.vue")['default']
    'LazyDashboardReport': typeof import("../components/dashboard/report.vue")['default']
    'LazyDashboardSalesdetails': typeof import("../components/dashboard/salesdetails.vue")['default']
    'LazyDashboardSoldout': typeof import("../components/dashboard/soldout.vue")['default']
    'LazyDashboardTimeline': typeof import("../components/dashboard/timeline.vue")['default']
    'LazyLayoutCustomizer': typeof import("../components/layout/customizer.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/footer/index.vue")['default']
    'LazyLayoutHeaderAttachment': typeof import("../components/layout/header/attachment.vue")['default']
    'LazyLayoutHeader': typeof import("../components/layout/header/index.vue")['default']
    'LazyLayoutHeaderMessage': typeof import("../components/layout/header/message.vue")['default']
    'LazyLayoutHeaderNotification': typeof import("../components/layout/header/notification.vue")['default']
    'LazyLayoutSidebar': typeof import("../components/layout/sidebar/index.vue")['default']
    'LazyLoader': typeof import("../components/loader.vue")['default']
    'LazyLogin': typeof import("../components/login/index.vue")['default']
    'LazyMapWorldmap': typeof import("../components/map/worldmap.vue")['default']
    'LazyMypropertiesAddproperty': typeof import("../components/myproperties/addproperty.vue")['default']
    'LazyMypropertiesEditproperty': typeof import("../components/myproperties/editproperty.vue")['default']
    'LazyMypropertiesFavourites': typeof import("../components/myproperties/favourites.vue")['default']
    'LazyMypropertiesListing': typeof import("../components/myproperties/listing.vue")['default']
    'LazyMypropertiesPropertyDetails': typeof import("../components/myproperties/property-details.vue")['default']
    'LazyPage404': typeof import("../components/page404.vue")['default']
    'LazyPayment': typeof import("../components/payment/index.vue")['default']
    'LazyReport': typeof import("../components/report/index.vue")['default']
    'LazyReportRevenue': typeof import("../components/report/revenue.vue")['default']
    'LazyReportSales': typeof import("../components/report/sales.vue")['default']
    'LazyReportTranaction': typeof import("../components/report/tranaction.vue")['default']
    'LazySignup': typeof import("../components/signup/index.vue")['default']
    'LazyTypeAppartment': typeof import("../components/type/appartment.vue")['default']
    'LazyTypeCondominium': typeof import("../components/type/condominium.vue")['default']
    'LazyTypeCottage': typeof import("../components/type/cottage.vue")['default']
    'LazyTypeFamily': typeof import("../components/type/family.vue")['default']
    'LazyUserAdduser': typeof import("../components/user/adduser.vue")['default']
    'LazyUserAllusers': typeof import("../components/user/allusers.vue")['default']
    'LazyUserEdituser': typeof import("../components/user/edituser.vue")['default']
    'LazyUserFormwizardFirsttab': typeof import("../components/user/formwizard/firsttab.vue")['default']
    'LazyUserFormwizard': typeof import("../components/user/formwizard/index.vue")['default']
    'LazyUserFormwizardSecondtab': typeof import("../components/user/formwizard/secondtab.vue")['default']
    'LazyUserFormwizardThirdtab': typeof import("../components/user/formwizard/thirdtab.vue")['default']
    'LazyUserProfileFriends': typeof import("../components/user/profile/friends.vue")['default']
    'LazyUserProfile': typeof import("../components/user/profile/index.vue")['default']
    'LazyUserProfileInstallment': typeof import("../components/user/profile/installment.vue")['default']
    'LazyUserProfilePropertyandlearning': typeof import("../components/user/profile/propertyandlearning.vue")['default']
    'LazyUserProfileUserfollowing': typeof import("../components/user/profile/userfollowing.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AgentInvoiceDetails: typeof import("../components/agent/Invoice/details.vue")['default']
export const AgentInvoice: typeof import("../components/agent/Invoice/index.vue")['default']
export const AgentAddagent: typeof import("../components/agent/addagent.vue")['default']
export const AgentAgentwizard: typeof import("../components/agent/agentwizard.vue")['default']
export const AgentAllagent: typeof import("../components/agent/allagent.vue")['default']
export const AgentEditagent: typeof import("../components/agent/editagent.vue")['default']
export const AgentProfiledataAbout: typeof import("../components/agent/profiledata/about.vue")['default']
export const AgentProfiledata: typeof import("../components/agent/profiledata/index.vue")['default']
export const AgentProfiledataPropertyandearning: typeof import("../components/agent/profiledata/propertyandearning.vue")['default']
export const CommonBreadcrumb: typeof import("../components/common/breadcrumb/index.vue")['default']
export const CommonChartBarchart: typeof import("../components/common/chart/barchart.vue")['default']
export const CommonChartEarning: typeof import("../components/common/chart/earning.vue")['default']
export const CommonChartIncomechart: typeof import("../components/common/chart/incomechart.vue")['default']
export const CommonChartRevenue: typeof import("../components/common/chart/revenue.vue")['default']
export const CommonChartUsers: typeof import("../components/common/chart/users.vue")['default']
export const CommonInputfieldsNumberfield: typeof import("../components/common/inputfields/numberfield.vue")['default']
export const CommonInputfieldsStatusfield: typeof import("../components/common/inputfields/statusfield.vue")['default']
export const CommonInputfieldsTextarea: typeof import("../components/common/inputfields/textarea.vue")['default']
export const CommonInputfieldsTextfield: typeof import("../components/common/inputfields/textfield.vue")['default']
export const CommonListdata: typeof import("../components/common/listdata.vue")['default']
export const CommonMapsWorldmap: typeof import("../components/common/maps/worldmap.vue")['default']
export const CommonSocialicon: typeof import("../components/common/socialicon.vue")['default']
export const Customizer: typeof import("../components/customizer.vue")['default']
export const DashboardAssignees: typeof import("../components/dashboard/assignees.vue")['default']
export const DashboardChart: typeof import("../components/dashboard/chart.vue")['default']
export const Dashboard: typeof import("../components/dashboard/index.vue")['default']
export const DashboardMyproperties: typeof import("../components/dashboard/myproperties.vue")['default']
export const DashboardReport: typeof import("../components/dashboard/report.vue")['default']
export const DashboardSalesdetails: typeof import("../components/dashboard/salesdetails.vue")['default']
export const DashboardSoldout: typeof import("../components/dashboard/soldout.vue")['default']
export const DashboardTimeline: typeof import("../components/dashboard/timeline.vue")['default']
export const LayoutCustomizer: typeof import("../components/layout/customizer.vue")['default']
export const LayoutFooter: typeof import("../components/layout/footer/index.vue")['default']
export const LayoutHeaderAttachment: typeof import("../components/layout/header/attachment.vue")['default']
export const LayoutHeader: typeof import("../components/layout/header/index.vue")['default']
export const LayoutHeaderMessage: typeof import("../components/layout/header/message.vue")['default']
export const LayoutHeaderNotification: typeof import("../components/layout/header/notification.vue")['default']
export const LayoutSidebar: typeof import("../components/layout/sidebar/index.vue")['default']
export const Loader: typeof import("../components/loader.vue")['default']
export const Login: typeof import("../components/login/index.vue")['default']
export const MapWorldmap: typeof import("../components/map/worldmap.vue")['default']
export const MypropertiesAddproperty: typeof import("../components/myproperties/addproperty.vue")['default']
export const MypropertiesEditproperty: typeof import("../components/myproperties/editproperty.vue")['default']
export const MypropertiesFavourites: typeof import("../components/myproperties/favourites.vue")['default']
export const MypropertiesListing: typeof import("../components/myproperties/listing.vue")['default']
export const MypropertiesPropertyDetails: typeof import("../components/myproperties/property-details.vue")['default']
export const Page404: typeof import("../components/page404.vue")['default']
export const Payment: typeof import("../components/payment/index.vue")['default']
export const Report: typeof import("../components/report/index.vue")['default']
export const ReportRevenue: typeof import("../components/report/revenue.vue")['default']
export const ReportSales: typeof import("../components/report/sales.vue")['default']
export const ReportTranaction: typeof import("../components/report/tranaction.vue")['default']
export const Signup: typeof import("../components/signup/index.vue")['default']
export const TypeAppartment: typeof import("../components/type/appartment.vue")['default']
export const TypeCondominium: typeof import("../components/type/condominium.vue")['default']
export const TypeCottage: typeof import("../components/type/cottage.vue")['default']
export const TypeFamily: typeof import("../components/type/family.vue")['default']
export const UserAdduser: typeof import("../components/user/adduser.vue")['default']
export const UserAllusers: typeof import("../components/user/allusers.vue")['default']
export const UserEdituser: typeof import("../components/user/edituser.vue")['default']
export const UserFormwizardFirsttab: typeof import("../components/user/formwizard/firsttab.vue")['default']
export const UserFormwizard: typeof import("../components/user/formwizard/index.vue")['default']
export const UserFormwizardSecondtab: typeof import("../components/user/formwizard/secondtab.vue")['default']
export const UserFormwizardThirdtab: typeof import("../components/user/formwizard/thirdtab.vue")['default']
export const UserProfileFriends: typeof import("../components/user/profile/friends.vue")['default']
export const UserProfile: typeof import("../components/user/profile/index.vue")['default']
export const UserProfileInstallment: typeof import("../components/user/profile/installment.vue")['default']
export const UserProfilePropertyandlearning: typeof import("../components/user/profile/propertyandlearning.vue")['default']
export const UserProfileUserfollowing: typeof import("../components/user/profile/userfollowing.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAgentInvoiceDetails: typeof import("../components/agent/Invoice/details.vue")['default']
export const LazyAgentInvoice: typeof import("../components/agent/Invoice/index.vue")['default']
export const LazyAgentAddagent: typeof import("../components/agent/addagent.vue")['default']
export const LazyAgentAgentwizard: typeof import("../components/agent/agentwizard.vue")['default']
export const LazyAgentAllagent: typeof import("../components/agent/allagent.vue")['default']
export const LazyAgentEditagent: typeof import("../components/agent/editagent.vue")['default']
export const LazyAgentProfiledataAbout: typeof import("../components/agent/profiledata/about.vue")['default']
export const LazyAgentProfiledata: typeof import("../components/agent/profiledata/index.vue")['default']
export const LazyAgentProfiledataPropertyandearning: typeof import("../components/agent/profiledata/propertyandearning.vue")['default']
export const LazyCommonBreadcrumb: typeof import("../components/common/breadcrumb/index.vue")['default']
export const LazyCommonChartBarchart: typeof import("../components/common/chart/barchart.vue")['default']
export const LazyCommonChartEarning: typeof import("../components/common/chart/earning.vue")['default']
export const LazyCommonChartIncomechart: typeof import("../components/common/chart/incomechart.vue")['default']
export const LazyCommonChartRevenue: typeof import("../components/common/chart/revenue.vue")['default']
export const LazyCommonChartUsers: typeof import("../components/common/chart/users.vue")['default']
export const LazyCommonInputfieldsNumberfield: typeof import("../components/common/inputfields/numberfield.vue")['default']
export const LazyCommonInputfieldsStatusfield: typeof import("../components/common/inputfields/statusfield.vue")['default']
export const LazyCommonInputfieldsTextarea: typeof import("../components/common/inputfields/textarea.vue")['default']
export const LazyCommonInputfieldsTextfield: typeof import("../components/common/inputfields/textfield.vue")['default']
export const LazyCommonListdata: typeof import("../components/common/listdata.vue")['default']
export const LazyCommonMapsWorldmap: typeof import("../components/common/maps/worldmap.vue")['default']
export const LazyCommonSocialicon: typeof import("../components/common/socialicon.vue")['default']
export const LazyCustomizer: typeof import("../components/customizer.vue")['default']
export const LazyDashboardAssignees: typeof import("../components/dashboard/assignees.vue")['default']
export const LazyDashboardChart: typeof import("../components/dashboard/chart.vue")['default']
export const LazyDashboard: typeof import("../components/dashboard/index.vue")['default']
export const LazyDashboardMyproperties: typeof import("../components/dashboard/myproperties.vue")['default']
export const LazyDashboardReport: typeof import("../components/dashboard/report.vue")['default']
export const LazyDashboardSalesdetails: typeof import("../components/dashboard/salesdetails.vue")['default']
export const LazyDashboardSoldout: typeof import("../components/dashboard/soldout.vue")['default']
export const LazyDashboardTimeline: typeof import("../components/dashboard/timeline.vue")['default']
export const LazyLayoutCustomizer: typeof import("../components/layout/customizer.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/footer/index.vue")['default']
export const LazyLayoutHeaderAttachment: typeof import("../components/layout/header/attachment.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/header/index.vue")['default']
export const LazyLayoutHeaderMessage: typeof import("../components/layout/header/message.vue")['default']
export const LazyLayoutHeaderNotification: typeof import("../components/layout/header/notification.vue")['default']
export const LazyLayoutSidebar: typeof import("../components/layout/sidebar/index.vue")['default']
export const LazyLoader: typeof import("../components/loader.vue")['default']
export const LazyLogin: typeof import("../components/login/index.vue")['default']
export const LazyMapWorldmap: typeof import("../components/map/worldmap.vue")['default']
export const LazyMypropertiesAddproperty: typeof import("../components/myproperties/addproperty.vue")['default']
export const LazyMypropertiesEditproperty: typeof import("../components/myproperties/editproperty.vue")['default']
export const LazyMypropertiesFavourites: typeof import("../components/myproperties/favourites.vue")['default']
export const LazyMypropertiesListing: typeof import("../components/myproperties/listing.vue")['default']
export const LazyMypropertiesPropertyDetails: typeof import("../components/myproperties/property-details.vue")['default']
export const LazyPage404: typeof import("../components/page404.vue")['default']
export const LazyPayment: typeof import("../components/payment/index.vue")['default']
export const LazyReport: typeof import("../components/report/index.vue")['default']
export const LazyReportRevenue: typeof import("../components/report/revenue.vue")['default']
export const LazyReportSales: typeof import("../components/report/sales.vue")['default']
export const LazyReportTranaction: typeof import("../components/report/tranaction.vue")['default']
export const LazySignup: typeof import("../components/signup/index.vue")['default']
export const LazyTypeAppartment: typeof import("../components/type/appartment.vue")['default']
export const LazyTypeCondominium: typeof import("../components/type/condominium.vue")['default']
export const LazyTypeCottage: typeof import("../components/type/cottage.vue")['default']
export const LazyTypeFamily: typeof import("../components/type/family.vue")['default']
export const LazyUserAdduser: typeof import("../components/user/adduser.vue")['default']
export const LazyUserAllusers: typeof import("../components/user/allusers.vue")['default']
export const LazyUserEdituser: typeof import("../components/user/edituser.vue")['default']
export const LazyUserFormwizardFirsttab: typeof import("../components/user/formwizard/firsttab.vue")['default']
export const LazyUserFormwizard: typeof import("../components/user/formwizard/index.vue")['default']
export const LazyUserFormwizardSecondtab: typeof import("../components/user/formwizard/secondtab.vue")['default']
export const LazyUserFormwizardThirdtab: typeof import("../components/user/formwizard/thirdtab.vue")['default']
export const LazyUserProfileFriends: typeof import("../components/user/profile/friends.vue")['default']
export const LazyUserProfile: typeof import("../components/user/profile/index.vue")['default']
export const LazyUserProfileInstallment: typeof import("../components/user/profile/installment.vue")['default']
export const LazyUserProfilePropertyandlearning: typeof import("../components/user/profile/propertyandlearning.vue")['default']
export const LazyUserProfileUserfollowing: typeof import("../components/user/profile/userfollowing.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
